### ISSUE TITLE
Unable to connect to backend - Warning: Missing argument 1 for FM\ElFinderPHP\Connector\ElFinderConnector::run()

### ISSUE THREAD

**Issue by wassimjahid** [helios-ag/ElFinderPHP#23]
Hello Eveybody,
I'm working in a symfony project and I have a problem with browsing server in ckeditor for inserting images.
I'm using **"Trsteel/ckeditor-bundle": "~1.8"** and **"helios-ag/fm-elfinder-bundle": "~4.0"**. When I try to browse the server to add image I have this alert: **Unable to connect to backend** and this error:
> Warning: Missing argument 1 for
> FM\ElFinderPHP\Connector\ElFinderConnector::run(), called in
> C:\wamp\www\awb\vendor\helios-ag\fm-elfinder-bundle\Loader\ElFinderLoader.php
> on line 63 and defined

Can someone help me please?

**Comment by nicolasmure** [comment]
Hi,

Please have a look to #22

**Comment by wassimjahid** [comment]
Hi,
I didn't have the error anymore but I got a blank page when I click browse server.
Here is my config.yml:

trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    transformers: []
    toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'tools']
    toolbar_groups:
        document: ['Source','-','Save','-','Templates']
        clipboard: ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo']
        editing: ['Find','Replace','-','SelectAll']
        basicstyles: ['Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat']
        paragraph: ['NumberedList','BulletedList','-','Outdent','Indent','-','JustifyLeft', 'JustifyCenter','JustifyRight','JustifyBlock']
        links: ['Link','Unlink','Anchor']
        insert: ['Image','Flash','Table','HorizontalRule']
        styles: ['Styles','Format']
        tools: ['Maximize', 'ShowBlocks']
    ui_color: '#ffffff'
    startup_outline_blocks: false
    width: 100% #Integer or %
    height: 300 #Integer or %
    language: 'fr'
    # filebrowser_upload_url:
    #     url: relative-url.php?type=file
    filebrowser_image_browse_url:
        route: elfinder
        route_parameters:
            instance: default

fm_elfinder:
    instances:
        default:
            locale: %locale% 
            editor: ckeditor
            fullscreen: true
            include_assets: true 
            connector:
                debug: false 
                roots:      
                    uploads:
                        show_hidden: false
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 6M

Any idea ?
Thanks
