### ISSUE TITLE
Flysystem driver not displaying folder

### ISSUE THREAD

**Issue by hoangnd25** [helios-ag/ElFinderPHP#27]
I'm using s3 adapter. However, I think other adapters will behave similarly to this.

This code in _stat function (ElFinderVolumeFlysystem) prevent folders from displaying:

```
        // If not exists, return empty
        if ( !$this->fs->has($path)) {
            return array();
        }
```

According to this https://github.com/thephpleague/flysystem/issues/132
fs->has function can only check file, not folder. Therefore, all the folders are not displaying.

This code can fix this
```
        // If not exists, return empty
        if ( !$this->fs->has($path)) {
            return $stat;
        }
```

However, I don't how other adapters behave. I also can't find a way to check if the adapter is s3

**Comment by barryvdh** [comment]
Should be fixed with https://github.com/barryvdh/elfinder-flysystem-driver/commit/c1c099b249147b64c2a269ed3c571fedaba5dc57

**Comment by helios-ag** [comment]
Thank you @barryvdh!
