### ISSUE TITLE
function execute($queryParameters)  and POST / No way to change a command argument on server side

### ISSUE THREAD

**Issue by Ronan-Lenor** [helios-ag/ElFinderPHP#29]
Hello,
i noticed that when i upload a file on ELFinder, i can't change the argument "upload_path" on the server side.
The reason is simple, the whole configuration is done in the POST x(

    $src    = $_SERVER["REQUEST_METHOD"] == 'POST' ? $_POST : $queryParameters;

can't you find a way to merge the $queryParameters with the POST parameters?
So my "upload_path" could write/overwrite the default "upload_path".

i don't know also the intire process inside Elfinder, but changing the "upload_path" from the client side, it isn't a security breach?

**Comment by helios-ag** [comment]
Ping @nicolasmure

**Comment by nicolasmure** [comment]
Hello,

Does the [home folder feature](https://github.com/helios-ag/FMElfinderBundle#use-multiple-upload-folder-by-instance "Use multiple upload folder by instance") can suit your needs?
Or have you tried to declare an other instance of elFinder in your `app/config/config.yml` file with your wanted `path` parameter?

I agree with you about the security breach, so can you also explain more your use case please to make the problem easier to understand?

**Comment by Ronan-Lenor** [comment]
Hello,

Yes thanks, i found that solution recently.

But consede that this actual script don't allow to access the entire ElFinder's Command properties =/
Hope you could improve that point on your future release :P

**Comment by Ronan-Lenor** [comment]
Hello again, i thought that my problen was resolved with your solution. but finally not.

So first, let's imagine that i have a such instance / homeFolder : domain.com/default/home
then inside it, i create a "image" directory.
inside it, i upload a .exe file.

Now, if before the upload i change the homefolder on the event onPreExecute:

    $Request->attributes->set('homeFolder', $event->getHomeFolder().'/control');

i get an error "ERROR_TRGDIR_NOT_FOUND".
with few research, i noticed that in the ElFinderVolumeDriver.php > function file() 
the $path return " uploads/home/control\image" which of course doesn't exist.

and here, i'm stuck. well, i could create an heavy solution where i create and delete some new Directory. but i'm sure that you can provide some more conveniente solution :P isn't it? :D

**Comment by nicolasmure** [comment]
Oh ok,

then why don't you make sure the folder you're setting with your preExecute eventListener actually exists? If it doesn't exists, create one using the [filesystem component](http://symfony.com/doc/current/components/filesystem/introduction.html "The Filesystem Component ")

**Comment by Ronan-Lenor** [comment]
Well, from onPreExecute i don't find how to get the directory which ElFinder is uploading
(noting in the $Request or $Event about it)

**Comment by nicolasmure** [comment]
Yes, elFinder uses hashes to store its informations about files and folders. Maybe the comments in [this PR](https://github.com/helios-ag/FMElfinderBundle/pull/128 "Command execution events + subrequests support + volume_id setting") can help you.
That's how I do to manage thumbnails with liipImagineBundle when I upload/delete an image file with elFinder. In fact, have to make a subrequest with the `info` command to get the image path.

But if you're hooking into a `upload` command (i.e. an HTTP POST request), subrequests may not work because of [this line](https://github.com/helios-ag/ElFinderPHP/blob/master/src/Connector/ElFinderConnector.php#L73) :
```php
$src = $_SERVER["REQUEST_METHOD"] == 'POST' ? $_POST : $queryParameters;
```
than, maybe you could try to edit this line as it :
```php
$src = array_merge($_POST, $queryParameters);
```
and make a new PR :wink:

**Comment by nicolasmure** [comment]
If you look to the [$_POST](https://github.com/helios-ag/ElFinderPHP/blob/master/src/Connector/ElFinderConnector.php#L73) parameters when you're uploading your file, you'll see that it's an array with 2 keys :
- `cmd` which contains the command name to execute
- and `target` which contains an hash to identify the folder to upload to.

If you make a subrequest with the `info` command and the target parameter from the $_POST array, you'll get infos about the upload dir.


An other workaround would be to let elFinder upload you file normally (i.e. no preExec eventListener), and then move the uploaded file in your custom directory with a postExec eventListener.

**Comment by nicolasmure** [comment]
If you try to upload a file and have firebug (or any other tool) open, then look to the POST request response : elFinder controller returns the following json response : 
```json
{
    "removed": [],
    "added": [
        {
            "hash": "l1_Zm9sZGVyL0JpcmQuanBn",
            "name": "Bird.jpg",
            "read": 1,
            "ts": 1445356113,
            "write": 1,
            "tmb": 1,
            "mime": "image/jpeg",
            "phash": "l1_Zm9sZGVy",
            "path": "10/folder/Bird.jpg",
            "size": 63057
        }
    ]
}
You can see a `path` key indicating where the file has been stored to.
This response is accessible as an array by calling the `ElFinderPostExecutionEvent::getResult` function. You'll then be able to move your file where you want.
```

**Comment by Ronan-Lenor** [comment]
Thanks,
but for security reason, i can't allow to let the user access the files between 2 request.

that's why i have to change the upload path to a restricted area where i zip the files before moving it to the expected directory.

that "info" trick is good for the PreExecution. but as you will probably accept a PR for let develloper use the command's parameters on a POST request, then i prefer use it :D 
By doing so, i would avoid a useless request for me server :P

**Comment by nicolasmure** [comment]
By using a postExec eventListener, you won't have any sub requests and your zip'n'move operation will be transparent to the user.
Take a look to the following example :
```php
// Acme/MyBundle/EventListener/ElFinder/PostExecutionEventListener.php
<?php
class PostExecutionEventListener
{
    public function onPostExecute(ElFinderPostExecutionEvent $event)
    {
        // be sure you're on an upload command
        if ($event->getCommand() != 'upload') {
            return;
        }
        $result = $event->getResult();
        foreach ($result['added'] as $key => $value) {
            $filepath = $value['path']
            // be sure you've uploaded a file you want to zip'n'move by checking its extension and its mimetype
            if (is_file_ok($filepath) === false) { // you can implement is_file_ok using $value['name'] and $value['mime']
                continue;
            }
            try {
                zip_file($filepath);
                move_file($filepath, 'new/destination');
            } catch (ZipOrMoveException $e) { // any exception thrown by the zip or by the move operation
                remove_file($filepath); // do not keep the original file as you can't handle it
            }
            unset($result['added'][$key]); // do not send to elFinder client infos about the file.
        }
        // updating the result to send back to the client
        // to avoid elFinder.js to make operations on the moved files
        $event->setResult($result);
    }
}
```
Doing so, I think your file will be uploaded (+zipped and moved) and you won't see it in the current folder after the upload on
elFinder.js client.

**Comment by Ronan-Lenor** [comment]
But by doing so, the original file will be accessible during the zipping process.

**Comment by nicolasmure** [comment]
Yep, that's right, but do you upload files that takes more than some milliseconds to zip?
Text file are usually lightweight.

**Comment by Ronan-Lenor** [comment]
lol, it's not profesionnal at all! x)

**Comment by nicolasmure** [comment]
Yes, seems legit then if you want to be sure the file isn't uploaded at all in the current folder...
